# Generated by Django 3.0.8 on 2020-08-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54, unique=True)),
                ('ra', models.DecimalField(decimal_places=8, max_digits=11)),
                ('dec', models.DecimalField(decimal_places=8, max_digits=11)),
                ('observations_number', models.IntegerField(blank=True, default=0, null=True)),
                ('magnitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('importance', models.IntegerField(default=0)),
                ('days_from_last_observations', models.IntegerField(blank=True, default=0, null=True)),
                ('cadence', models.IntegerField(default=1)),
                ('priority', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
