# Generated by Django 3.0.8 on 2021-02-23 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('name', models.CharField(max_length=54, primary_key=True, serialize=False, unique=True)),
                ('ra', models.DecimalField(decimal_places=8, max_digits=11)),
                ('dec', models.DecimalField(decimal_places=8, max_digits=11)),
                ('magnitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('p', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('m0', models.DecimalField(blank=True, decimal_places=8, default=1, max_digits=16, null=True)),
                ('cadence', models.IntegerField(default=1)),
                ('priority', models.DecimalField(decimal_places=1, max_digits=5)),
                ('note', models.CharField(blank=True, max_length=34, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targets.TargetGroup')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
