# Generated by Django 3.0.8 on 2020-08-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54, unique=True)),
                ('ra', models.DecimalField(decimal_places=8, max_digits=11)),
                ('dec', models.DecimalField(decimal_places=8, max_digits=11)),
                ('observations_number', models.IntegerField(blank=True, default=0, null=True)),
                ('magnitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('days_from_last_observations', models.IntegerField(blank=True, default=0, null=True)),
                ('cadence', models.IntegerField(default=1)),
                ('priority', models.DecimalField(decimal_places=1, max_digits=5)),
                ('note', models.CharField(blank=True, max_length=34, null=True)),
                ('group', models.ForeignKey(default='common', on_delete=django.db.models.deletion.SET_DEFAULT, to='targets.TargetGroup')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
