# Generated by Django 3.0.8 on 2020-08-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_auto_20200806_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='m0',
            field=models.DecimalField(blank=True, decimal_places=7, default=1, max_digits=14, null=True),
        ),
    ]
