# Generated by Django 3.0.8 on 2020-09-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_auto_20200806_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='m0',
            field=models.DecimalField(blank=True, decimal_places=8, default=1, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='p',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
    ]
